# Generated by Django 4.1 on 2024-04-02 18:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Clinica',
            fields=[
                ('idClinica', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('Nombre', models.CharField(max_length=45, null=True)),
                ('Codigo', models.CharField(max_length=45, null=True)),
                ('Domicilio', models.CharField(max_length=45, null=True)),
                ('Cp', models.CharField(max_length=45, null=True)),
                ('Ciudad', models.CharField(max_length=45, null=True)),
                ('Telefono', models.CharField(max_length=45, null=True)),
                ('Fax', models.CharField(max_length=45, null=True)),
                ('Correo', models.EmailField(max_length=45, null=True)),
                ('SitioWeb', models.URLField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='EstudioUltrasonido',
            fields=[
                ('idEstudioUltrasonido', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('Fecha', models.DateField(null=True)),
                ('Hora', models.TimeField(null=True)),
                ('Observaciones', models.TextField(null=True)),
                ('Clinica', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.clinica')),
            ],
        ),
        migrations.CreateModel(
            name='ImagenUltrasonido',
            fields=[
                ('idImagenUltrasonido', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('Imagen', models.ImageField(null=True, upload_to='imagenes/')),
                ('Tipo', models.CharField(max_length=45, null=True)),
                ('Fecha', models.DateTimeField(null=True)),
                ('Notas', models.CharField(max_length=255, null=True)),
                ('Calificacion', models.PositiveSmallIntegerField(null=True)),
                ('EstudioUltrasonido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.estudioultrasonido')),
            ],
        ),
        migrations.CreateModel(
            name='Medico',
            fields=[
                ('idMedico', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('Nombre', models.CharField(max_length=45, null=True)),
                ('Apellido', models.CharField(max_length=45, null=True)),
                ('Especialidad', models.CharField(max_length=45, null=True)),
                ('Cedula', models.CharField(max_length=45, null=True)),
                ('Telefono', models.CharField(max_length=45, null=True)),
                ('Correo', models.EmailField(max_length=45, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='MensajeWhatsApp',
            fields=[
                ('idMensaje', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('destinatario', models.CharField(max_length=20)),
                ('contenido', models.TextField()),
                ('fecha_envio', models.DateTimeField(auto_now_add=True)),
                ('enviado', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='TipoEstudio',
            fields=[
                ('idTipoEstudio', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('Nombre', models.CharField(max_length=45, null=True)),
                ('Descripcion', models.TextField(null=True)),
                ('Imagen', models.ImageField(null=True, upload_to='tipo_estudio/')),
                ('Duracion', models.FloatField(null=True)),
                ('Codigo', models.CharField(max_length=45, null=True)),
                ('Costo', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('Observaciones', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='VideoUltrasonido',
            fields=[
                ('idVideoUltrasonido', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('Video', models.FileField(null=True, upload_to='videos/')),
                ('Fecha', models.DateTimeField(null=True)),
                ('Tipo', models.CharField(max_length=45, null=True)),
                ('Notas', models.CharField(max_length=255, null=True)),
                ('Calidad', models.CharField(max_length=45, null=True)),
                ('EstudioUltrasonido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.estudioultrasonido')),
            ],
        ),
        migrations.CreateModel(
            name='RespuestaBot',
            fields=[
                ('idRespuesta', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('contenido_respuesta', models.TextField()),
                ('fecha_respuesta', models.DateTimeField(auto_now_add=True)),
                ('mensaje_original', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.mensajewhatsapp')),
            ],
        ),
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('idPaciente', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('Username', models.CharField(max_length=45, null=True)),
                ('Password', models.CharField(max_length=255)),
                ('Nombre', models.CharField(max_length=45, null=True)),
                ('Apellido', models.CharField(max_length=45, null=True)),
                ('Telefono', models.CharField(max_length=45, null=True)),
                ('Correo', models.EmailField(max_length=45, null=True)),
                ('FechaNacimiento', models.DateField(null=True)),
                ('Sexo', models.CharField(max_length=1, null=True)),
                ('Direccion', models.CharField(max_length=100, null=True)),
                ('Ciudad', models.CharField(max_length=45, null=True)),
                ('Estado', models.CharField(max_length=45, null=True)),
                ('Pais', models.CharField(max_length=45, null=True)),
                ('usuario', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='mensajewhatsapp',
            name='Paciente',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.paciente'),
        ),
        migrations.CreateModel(
            name='Medicion',
            fields=[
                ('idMedicion', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('Nombre', models.CharField(max_length=45, null=True)),
                ('Tipo', models.CharField(max_length=45, null=True)),
                ('Contenido', models.TextField(null=True)),
                ('Valor', models.FloatField(null=True)),
                ('Unidad', models.CharField(max_length=45, null=True)),
                ('RangoNormal', models.CharField(max_length=45, null=True)),
                ('Interpretacion', models.CharField(max_length=100, null=True)),
                ('ImagenUltrasonido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.imagenultrasonido')),
            ],
        ),
        migrations.CreateModel(
            name='InformeMedico',
            fields=[
                ('idInformeMedico', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('Detalles', models.TextField(null=True)),
                ('Notas', models.CharField(max_length=255, null=True)),
                ('fecha', models.DateField(null=True)),
                ('Doctor', models.CharField(max_length=45, null=True)),
                ('Diagnostico', models.TextField(null=True)),
                ('Recomendaciones', models.TextField(null=True)),
                ('EstudioUltrasonido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.estudioultrasonido')),
            ],
        ),
        migrations.CreateModel(
            name='Etiqueta',
            fields=[
                ('idEtiqueta', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('Nombre', models.CharField(max_length=45, null=True)),
                ('Tipo', models.CharField(max_length=45, null=True)),
                ('Descripcion', models.CharField(max_length=255, null=True)),
                ('Coordernadas', models.CharField(max_length=100, null=True)),
                ('Color', models.CharField(max_length=20, null=True)),
                ('ImagenUltrasonido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.imagenultrasonido')),
            ],
        ),
        migrations.AddField(
            model_name='estudioultrasonido',
            name='Medico',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.medico'),
        ),
        migrations.AddField(
            model_name='estudioultrasonido',
            name='Paciente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.paciente'),
        ),
        migrations.AddField(
            model_name='estudioultrasonido',
            name='TipoEstudio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.tipoestudio'),
        ),
    ]
