# Generated by Django 4.1 on 2024-04-02 18:30

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paciente',
            name='idPaciente',
            field=models.UUIDField(editable=False, primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name='CitaMedica',
            fields=[
                ('idCitaMedica', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('Fecha', models.DateField(null=True)),
                ('Hora', models.TimeField(null=True)),
                ('Observaciones', models.TextField(null=True)),
                ('Clinica', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.clinica')),
                ('Medico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.medico')),
                ('Paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.paciente')),
                ('TipoEstudio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.tipoestudio')),
            ],
        ),
        migrations.AddField(
            model_name='estudioultrasonido',
            name='CitaMedica',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.citamedica'),
        ),
    ]
