# Generated by Django 4.1 on 2024-04-02 18:45

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_paciente_idpaciente_citamedica_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paciente',
            name='idPaciente',
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False),
        ),
    ]
