# Generated by Django 4.1 on 2024-04-02 21:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_citamedica_idcitamedica_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='citamedica',
            name='Clinica',
        ),
        migrations.RemoveField(
            model_name='citamedica',
            name='Medico',
        ),
        migrations.RemoveField(
            model_name='citamedica',
            name='Paciente',
        ),
        migrations.RemoveField(
            model_name='citamedica',
            name='TipoEstudio',
        ),
    ]
